[pytest]

addopts= -v --cov=models --cov=services --cov=config --cov=controllers  --cov-report=term-missing --cov-fail-under=80

""" -v  -> Verbose
    --cov  -> write the folder to test
    --cov-fail-under=x  -> Show up covers under 80%

    Run in terminal: pytest
"""